name: Check Upstream Updates

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/qbittorrent/docker-qbittorrent-nox.git
          git fetch upstream

      - name: Check for updates
        id: check
        run: |
          BEHIND_BY=$(git rev-list --count HEAD..upstream/main)
          echo "behind_by=$BEHIND_BY" >> $GITHUB_OUTPUT
          if [ "$BEHIND_BY" -gt 0 ]; then
            echo "updates_available=true" >> $GITHUB_OUTPUT
          else
            echo "updates_available=false" >> $GITHUB_OUTPUT
          fi

      - name: Create issue if updates available
        if: steps.check.outputs.updates_available == 'true'
        uses: actions/github-script@v8
        with:
          script: |
            const [owner, repo] = '${{ github.repository }}'.split('/');
            const behindBy = parseInt('${{ steps.check.outputs.behind_by }}');
            
            await github.rest.issues.create({
              owner,
              repo,
              title: `⚠️ Repository is ${behindBy} commits behind upstream`,
              body: `Your fork is currently ${behindBy} commits behind the upstream repository.
            
              To sync your fork:
              1. \`git fetch upstream\`
              2. \`git checkout main\`
              3. \`git merge upstream/main\`
              4. \`git push origin main\``
            });
