name: Docker Image CI

on:
  push:
    tags: [ '[0-9].[0-9].[0-9]-[0-9]+' ]

permissions:
  contents: read
  packages: write

env:
  QBT_VERSION: "5.0.3"
  LIBBT_VERSION: "v1.2.20"
  GHCR_REPOSITORY: ghcr.io/arkandias/qbittorrent
  DOCKERHUB_REPOSITORY: jhauseux/qbittorrent

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check tag
        run: |
          if [[ ! "${GITHUB_REF_NAME}" =~ ^$(echo -n "$QBT_VERSION" | sed 's/\./\\./g')-[0-9]+$ ]]; then
            echo "Invalid tag format '${GITHUB_REF_NAME}'. Expected: ${QBT_VERSION}-NUMBER (e.g., ${QBT_VERSION}-0)" >> "${GITHUB_STEP_SUMMARY}"
            exit 1
          fi

      - name: Set variables
        id: vars
        run: |
          echo "date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> "${GITHUB_OUTPUT}"
          echo "version=${GITHUB_REF_NAME}" >> "${GITHUB_OUTPUT}"
          echo "ghcr_tags=${GHCR_REPOSITORY}:${GITHUB_REF_NAME},${GHCR_REPOSITORY}:latest" >> "${GITHUB_OUTPUT}"
          echo "dockerhub_tags=${DOCKERHUB_REPOSITORY}:${GITHUB_REF_NAME},${DOCKERHUB_REPOSITORY}:latest" >> "${GITHUB_OUTPUT}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.vars.outputs.ghcr_tags }},${{ steps.vars.outputs.dockerhub_tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            QBT_VERSION=${{ env.QBT_VERSION }}
            BUILD_DATE=${{ steps.vars.outputs.date }}
            VERSION=${{ steps.vars.outputs.version }}
            VCS_REF=${{ github.sha }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.DOCKERHUB_REPOSITORY }}
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./README.md
